name: Convert PDF to Image

on:
  push:
    branches:
      - main
    paths:
      - 'resume.tex' # only trigger when there is a change to latex file

jobs:
  pdf_to_image:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Build and run docker
      run: |
        docker build -t latex-pdf-to-image .
        docker run --rm -v $(pwd):/app latex-pdf-to-image

    # Check if the image was generated and commit it back
    - name: Commit and push generated image
      run: |
        if [ -f resume.png ]; then
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add resume.png
          git commit -m "Add screenshot from latest LaTeX PDF"
          git push https://x-access-token:${{ secrets.RESUME_PAT }}@github.com/kdk1116/Resume.git
        else
          echo "No screenshot generated, skipping commit."
        fi
